LOGIN_LINK="http://cdl.ddns.net:4098/cgi-bin/kchang_cdlcapital/front/login.py"
VALIDATE_LOGIN_LINK="http://cdl.ddns.net:4098/cgi-bin/kchang_cdlcapital/front/validate_login.py"
HOME_LINK="http://cdl.ddns.net:4098/cgi-bin/kchang_cdlcapital/front/home.py"

FILTER_DROPDOWN_LINK="http://cdl.ddns.net:4098/cgi-bin/kchang_cdlcapital/scripts/generate_filter_dropdown.py"
DEPOSIT_LINK="http://cdl.ddns.net:4098/cgi-bin/kchang_cdlcapital/service/deposit_service.py"
UPLOAD_LINK="http://cdl.ddns.net:4098/cgi-bin/kchang_cdlcapital/service/upload_profile_information.py"
TRANSACTION_LINK="http://cdl.ddns.net:4098/cgi-bin/kchang_cdlcapital/scripts/transaction_user_script.py"
ACTIVE_STOCKS_VOLUMECHANGE_LINK="http://cdl.ddns.net:4098/cgi-bin/kchang_cdlcapital/service/active_stocks_volumechange_service.py"
ACTIVE_STOCKS_PERCENTCHANGE_LINK="http://cdl.ddns.net:4098/cgi-bin/kchang_cdlcapital/service/active_stocks_percentchange_service.py"
DROPDOWN_LINK="http://cdl.ddns.net:4098/cgi-bin/kchang_cdlcapital/service/generate_sell_dropdown.py"
DISPLAY_ALGORITHMS_LINK="http://cdl.ddns.net:4098/cgi-bin/kchang_cdlcapital/scripts/display_algorithms.py"
EXECUTE_ALGORITHMS_LINK="http://cdl.ddns.net:4098/cgi-bin/kchang_cdlcapital/scripts/execute_algo.py"
GET_ACTIVE_ALGORITHMS_LINK="http://cdl.ddns.net:4098/cgi-bin/kchang_cdlcapital/scripts/get_active_algorithms.py"
PORTFOLIO_LINK="http://cdl.ddns.net:4098/cgi-bin/kchang_cdlcapital/service/portfolio_distribution.py"
ALGORITHM_GRAPH_LINK="http://cdl.ddns.net:4098/cgi-bin/kchang_cdlcapital/scripts/algorithm_graph.py"
ALGORITHM_GRAPH_DROPDOWN_LINK="http://cdl.ddns.net:4098/cgi-bin/kchang_cdlcapital/scripts/generate_algorithm_graph_dropdown.py"

UPDATE_PASSWORD_LINK="http://cdl.ddns.net:4098/cgi-bin/kchang_cdlcapital/scripts/update_password.py"
SCRIPTS_LINK="/usr/lib/cgi-bin/kchang_cdlcapital/scripts/"
UPDATE_USER_LINK="http://cdl.ddns.net:4098/cgi-bin/kchang_cdlcapital/scripts/update_user.py"
CREATE_USER_LINK="http://cdl.ddns.net:4098/cgi-bin/kchang_cdlcapital/scripts/create_user.py"

MODELS_LINK="/usr/lib/cgi-bin/kchang_cdlcapital/models/"
ALGORITHMS_LINK="/usr/lib/cgi-bin/kchang_cdlcapital/algorithms/"

DB_HOST="localhost"
DB_USER="root"
DB_PASSWORD="mmGr2016"
DB_NAME="cdlcapital"
DATABASE_LINK="/usr/lib/cgi-bin/kchang_cdlcapital/back/"
DAO_LINK="/usr/lib/cgi-bin/kchang_cdlcapital/dao/"
PDO_LINK="/usr/lib/cgi-bin/kchang_cdlcapital/back/PDO.py"

YQL_LINK="http://cdl.ddns.net:4098/cgi-bin/kchang_cdlcapital/yql/yahoo_finance_class.py"

SERVICE_LINK="/usr/lib/cgi-bin/kchang_cdlcapital/service/"
STOCK_LINK="http://cdl.ddns.net:4098/cgi-bin/kchang_cdlcapital/scripts/autocomplete.py"
